/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AuthenticatedMyMenuRouteImport } from './routes/_authenticated/my-menu'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminQrRouteImport } from './routes/_authenticated/admin.qr'
import { Route as AuthenticatedAdminRestaurantsIndexRouteImport } from './routes/_authenticated/admin.restaurants.index'
import { Route as AuthenticatedAdminRestaurantsNewRouteImport } from './routes/_authenticated/admin.restaurants.new'
import { Route as AuthenticatedAdminRestaurantsIdRouteImport } from './routes/_authenticated/admin.restaurants.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyMenuRoute = AuthenticatedMyMenuRouteImport.update({
  id: '/my-menu',
  path: '/my-menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQrRoute = AuthenticatedAdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRestaurantsIndexRoute =
  AuthenticatedAdminRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsNewRoute =
  AuthenticatedAdminRestaurantsNewRouteImport.update({
    id: '/restaurants/new',
    path: '/restaurants/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsIdRoute =
  AuthenticatedAdminRestaurantsIdRouteImport.update({
    id: '/restaurants/$id',
    path: '/restaurants/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-menu': typeof AuthenticatedMyMenuRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/admin/restaurants/': typeof AuthenticatedAdminRestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-menu': typeof AuthenticatedMyMenuRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-menu': typeof AuthenticatedMyMenuRoute
  '/m/$slug': typeof MSlugRoute
  '/_authenticated/admin/qr': typeof AuthenticatedAdminQrRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/_authenticated/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/_authenticated/admin/restaurants/': typeof AuthenticatedAdminRestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/my-menu'
    | '/m/$slug'
    | '/admin/qr'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
    | '/admin/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-menu'
    | '/m/$slug'
    | '/admin/qr'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
    | '/admin/restaurants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/my-menu'
    | '/m/$slug'
    | '/_authenticated/admin/qr'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/restaurants/$id'
    | '/_authenticated/admin/restaurants/new'
    | '/_authenticated/admin/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-menu': {
      id: '/_authenticated/my-menu'
      path: '/my-menu'
      fullPath: '/my-menu'
      preLoaderRoute: typeof AuthenticatedMyMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qr': {
      id: '/_authenticated/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AuthenticatedAdminQrRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/': {
      id: '/_authenticated/admin/restaurants/'
      path: '/restaurants'
      fullPath: '/admin/restaurants/'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/new': {
      id: '/_authenticated/admin/restaurants/new'
      path: '/restaurants/new'
      fullPath: '/admin/restaurants/new'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/$id': {
      id: '/_authenticated/admin/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminQrRoute: typeof AuthenticatedAdminQrRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRestaurantsIdRoute: typeof AuthenticatedAdminRestaurantsIdRoute
  AuthenticatedAdminRestaurantsNewRoute: typeof AuthenticatedAdminRestaurantsNewRoute
  AuthenticatedAdminRestaurantsIndexRoute: typeof AuthenticatedAdminRestaurantsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminQrRoute: AuthenticatedAdminQrRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRestaurantsIdRoute: AuthenticatedAdminRestaurantsIdRoute,
  AuthenticatedAdminRestaurantsNewRoute: AuthenticatedAdminRestaurantsNewRoute,
  AuthenticatedAdminRestaurantsIndexRoute:
    AuthenticatedAdminRestaurantsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyMenuRoute: typeof AuthenticatedMyMenuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyMenuRoute: AuthenticatedMyMenuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
