/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIntroRouteImport } from './routes/app-intro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AuthenticatedSuperAdminGalleryRouteImport } from './routes/_authenticated/super-admin-gallery'
import { Route as AuthenticatedMyMenuRouteImport } from './routes/_authenticated/my-menu'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin.templates'
import { Route as AuthenticatedAdminSuperDashboardRouteImport } from './routes/_authenticated.admin.super-dashboard'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRestaurantDashboardRouteImport } from './routes/_authenticated.admin.restaurant-dashboard'
import { Route as AuthenticatedAdminQrRouteImport } from './routes/_authenticated/admin.qr'
import { Route as AuthenticatedAdminMenuDesignsRouteImport } from './routes/_authenticated/admin/menu-designs'
import { Route as AuthenticatedAdminDesignStudioRouteImport } from './routes/_authenticated/admin/design-studio'
import { Route as AuthenticatedAdminRestaurantsIndexRouteImport } from './routes/_authenticated/admin.restaurants.index'
import { Route as AuthenticatedAdminRestaurantsNewRouteImport } from './routes/_authenticated/admin.restaurants.new'
import { Route as AuthenticatedAdminRestaurantsIdRouteImport } from './routes/_authenticated/admin.restaurants.$id'
import { Route as AuthenticatedSrcRoutesAuthenticatedAdminAuthRouteImport } from './routes/_authenticated/src/routes/_authenticated/admin/auth'
import { Route as AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRouteImport } from './routes/_authenticated/src/routes/_authenticated/admin/utes/m.$slug'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntroRoute = AppIntroRouteImport.update({
  id: '/app-intro',
  path: '/app-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminGalleryRoute =
  AuthenticatedSuperAdminGalleryRouteImport.update({
    id: '/super-admin-gallery',
    path: '/super-admin-gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyMenuRoute = AuthenticatedMyMenuRouteImport.update({
  id: '/my-menu',
  path: '/my-menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuperDashboardRoute =
  AuthenticatedAdminSuperDashboardRouteImport.update({
    id: '/super-dashboard',
    path: '/super-dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantDashboardRoute =
  AuthenticatedAdminRestaurantDashboardRouteImport.update({
    id: '/restaurant-dashboard',
    path: '/restaurant-dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQrRoute = AuthenticatedAdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMenuDesignsRoute =
  AuthenticatedAdminMenuDesignsRouteImport.update({
    id: '/menu-designs',
    path: '/menu-designs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDesignStudioRoute =
  AuthenticatedAdminDesignStudioRouteImport.update({
    id: '/design-studio',
    path: '/design-studio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsIndexRoute =
  AuthenticatedAdminRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsNewRoute =
  AuthenticatedAdminRestaurantsNewRouteImport.update({
    id: '/restaurants/new',
    path: '/restaurants/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsIdRoute =
  AuthenticatedAdminRestaurantsIdRouteImport.update({
    id: '/restaurants/$id',
    path: '/restaurants/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute =
  AuthenticatedSrcRoutesAuthenticatedAdminAuthRouteImport.update({
    id: '/src/routes/_authenticated/admin/auth',
    path: '/src/routes/admin/auth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute =
  AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRouteImport.update({
    id: '/src/routes/_authenticated/admin/utes/m/$slug',
    path: '/src/routes/admin/utes/m/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-intro': typeof AppIntroRoute
  '/auth': typeof AuthRoute
  '/splash': typeof SplashRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-menu': typeof AuthenticatedMyMenuRoute
  '/super-admin-gallery': typeof AuthenticatedSuperAdminGalleryRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/design-studio': typeof AuthenticatedAdminDesignStudioRoute
  '/admin/menu-designs': typeof AuthenticatedAdminMenuDesignsRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/restaurant-dashboard': typeof AuthenticatedAdminRestaurantDashboardRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/super-dashboard': typeof AuthenticatedAdminSuperDashboardRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/admin/restaurants/': typeof AuthenticatedAdminRestaurantsIndexRoute
  '/src/routes/admin/auth': typeof AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute
  '/src/routes/admin/utes/m/$slug': typeof AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-intro': typeof AppIntroRoute
  '/auth': typeof AuthRoute
  '/splash': typeof SplashRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/my-menu': typeof AuthenticatedMyMenuRoute
  '/super-admin-gallery': typeof AuthenticatedSuperAdminGalleryRoute
  '/m/$slug': typeof MSlugRoute
  '/admin/design-studio': typeof AuthenticatedAdminDesignStudioRoute
  '/admin/menu-designs': typeof AuthenticatedAdminMenuDesignsRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/restaurant-dashboard': typeof AuthenticatedAdminRestaurantDashboardRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/super-dashboard': typeof AuthenticatedAdminSuperDashboardRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsIndexRoute
  '/src/routes/admin/auth': typeof AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute
  '/src/routes/admin/utes/m/$slug': typeof AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app-intro': typeof AppIntroRoute
  '/auth': typeof AuthRoute
  '/splash': typeof SplashRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-menu': typeof AuthenticatedMyMenuRoute
  '/_authenticated/super-admin-gallery': typeof AuthenticatedSuperAdminGalleryRoute
  '/m/$slug': typeof MSlugRoute
  '/_authenticated/admin/design-studio': typeof AuthenticatedAdminDesignStudioRoute
  '/_authenticated/admin/menu-designs': typeof AuthenticatedAdminMenuDesignsRoute
  '/_authenticated/admin/qr': typeof AuthenticatedAdminQrRoute
  '/_authenticated/admin/restaurant-dashboard': typeof AuthenticatedAdminRestaurantDashboardRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/super-dashboard': typeof AuthenticatedAdminSuperDashboardRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
  '/_authenticated/admin/restaurants/new': typeof AuthenticatedAdminRestaurantsNewRoute
  '/_authenticated/admin/restaurants/': typeof AuthenticatedAdminRestaurantsIndexRoute
  '/_authenticated/src/routes/_authenticated/admin/auth': typeof AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute
  '/_authenticated/src/routes/_authenticated/admin/utes/m/$slug': typeof AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-intro'
    | '/auth'
    | '/splash'
    | '/unauthorized'
    | '/admin'
    | '/my-menu'
    | '/super-admin-gallery'
    | '/m/$slug'
    | '/admin/design-studio'
    | '/admin/menu-designs'
    | '/admin/qr'
    | '/admin/restaurant-dashboard'
    | '/admin/settings'
    | '/admin/super-dashboard'
    | '/admin/templates'
    | '/admin/videos'
    | '/admin/'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
    | '/admin/restaurants/'
    | '/src/routes/admin/auth'
    | '/src/routes/admin/utes/m/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-intro'
    | '/auth'
    | '/splash'
    | '/unauthorized'
    | '/my-menu'
    | '/super-admin-gallery'
    | '/m/$slug'
    | '/admin/design-studio'
    | '/admin/menu-designs'
    | '/admin/qr'
    | '/admin/restaurant-dashboard'
    | '/admin/settings'
    | '/admin/super-dashboard'
    | '/admin/templates'
    | '/admin/videos'
    | '/admin'
    | '/admin/restaurants/$id'
    | '/admin/restaurants/new'
    | '/admin/restaurants'
    | '/src/routes/admin/auth'
    | '/src/routes/admin/utes/m/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app-intro'
    | '/auth'
    | '/splash'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/my-menu'
    | '/_authenticated/super-admin-gallery'
    | '/m/$slug'
    | '/_authenticated/admin/design-studio'
    | '/_authenticated/admin/menu-designs'
    | '/_authenticated/admin/qr'
    | '/_authenticated/admin/restaurant-dashboard'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/super-dashboard'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/restaurants/$id'
    | '/_authenticated/admin/restaurants/new'
    | '/_authenticated/admin/restaurants/'
    | '/_authenticated/src/routes/_authenticated/admin/auth'
    | '/_authenticated/src/routes/_authenticated/admin/utes/m/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppIntroRoute: typeof AppIntroRoute
  AuthRoute: typeof AuthRoute
  SplashRoute: typeof SplashRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-intro': {
      id: '/app-intro'
      path: '/app-intro'
      fullPath: '/app-intro'
      preLoaderRoute: typeof AppIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin-gallery': {
      id: '/_authenticated/super-admin-gallery'
      path: '/super-admin-gallery'
      fullPath: '/super-admin-gallery'
      preLoaderRoute: typeof AuthenticatedSuperAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-menu': {
      id: '/_authenticated/my-menu'
      path: '/my-menu'
      fullPath: '/my-menu'
      preLoaderRoute: typeof AuthenticatedMyMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/super-dashboard': {
      id: '/_authenticated/admin/super-dashboard'
      path: '/super-dashboard'
      fullPath: '/admin/super-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminSuperDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurant-dashboard': {
      id: '/_authenticated/admin/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/admin/restaurant-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qr': {
      id: '/_authenticated/admin/qr'
      path: '/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AuthenticatedAdminQrRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu-designs': {
      id: '/_authenticated/admin/menu-designs'
      path: '/menu-designs'
      fullPath: '/admin/menu-designs'
      preLoaderRoute: typeof AuthenticatedAdminMenuDesignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/design-studio': {
      id: '/_authenticated/admin/design-studio'
      path: '/design-studio'
      fullPath: '/admin/design-studio'
      preLoaderRoute: typeof AuthenticatedAdminDesignStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/': {
      id: '/_authenticated/admin/restaurants/'
      path: '/restaurants'
      fullPath: '/admin/restaurants/'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/new': {
      id: '/_authenticated/admin/restaurants/new'
      path: '/restaurants/new'
      fullPath: '/admin/restaurants/new'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants/$id': {
      id: '/_authenticated/admin/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/src/routes/_authenticated/admin/auth': {
      id: '/_authenticated/src/routes/_authenticated/admin/auth'
      path: '/src/routes/admin/auth'
      fullPath: '/src/routes/admin/auth'
      preLoaderRoute: typeof AuthenticatedSrcRoutesAuthenticatedAdminAuthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/src/routes/_authenticated/admin/utes/m/$slug': {
      id: '/_authenticated/src/routes/_authenticated/admin/utes/m/$slug'
      path: '/src/routes/admin/utes/m/$slug'
      fullPath: '/src/routes/admin/utes/m/$slug'
      preLoaderRoute: typeof AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDesignStudioRoute: typeof AuthenticatedAdminDesignStudioRoute
  AuthenticatedAdminMenuDesignsRoute: typeof AuthenticatedAdminMenuDesignsRoute
  AuthenticatedAdminQrRoute: typeof AuthenticatedAdminQrRoute
  AuthenticatedAdminRestaurantDashboardRoute: typeof AuthenticatedAdminRestaurantDashboardRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSuperDashboardRoute: typeof AuthenticatedAdminSuperDashboardRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRestaurantsIdRoute: typeof AuthenticatedAdminRestaurantsIdRoute
  AuthenticatedAdminRestaurantsNewRoute: typeof AuthenticatedAdminRestaurantsNewRoute
  AuthenticatedAdminRestaurantsIndexRoute: typeof AuthenticatedAdminRestaurantsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDesignStudioRoute: AuthenticatedAdminDesignStudioRoute,
  AuthenticatedAdminMenuDesignsRoute: AuthenticatedAdminMenuDesignsRoute,
  AuthenticatedAdminQrRoute: AuthenticatedAdminQrRoute,
  AuthenticatedAdminRestaurantDashboardRoute:
    AuthenticatedAdminRestaurantDashboardRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSuperDashboardRoute: AuthenticatedAdminSuperDashboardRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRestaurantsIdRoute: AuthenticatedAdminRestaurantsIdRoute,
  AuthenticatedAdminRestaurantsNewRoute: AuthenticatedAdminRestaurantsNewRoute,
  AuthenticatedAdminRestaurantsIndexRoute:
    AuthenticatedAdminRestaurantsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyMenuRoute: typeof AuthenticatedMyMenuRoute
  AuthenticatedSuperAdminGalleryRoute: typeof AuthenticatedSuperAdminGalleryRoute
  AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute: typeof AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute
  AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute: typeof AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyMenuRoute: AuthenticatedMyMenuRoute,
  AuthenticatedSuperAdminGalleryRoute: AuthenticatedSuperAdminGalleryRoute,
  AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute:
    AuthenticatedSrcRoutesAuthenticatedAdminAuthRoute,
  AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute:
    AuthenticatedSrcRoutesAuthenticatedAdminUtesMSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppIntroRoute: AppIntroRoute,
  AuthRoute: AuthRoute,
  SplashRoute: SplashRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
